version: "3.7"

services:
  postgres:
    container_name: random_user_generator_db
    image: "postgres:13"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "./pg_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    restart: unless-stopped
